# Generated by Django 6.0 on 2025-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='time_schedule',
            field=models.DateTimeField(),
        ),
    ]
