# Generated by Django 6.0 on 2025-12-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0003_tableassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableassign',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
