# Generated by Django 6.0 on 2025-12-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0004_tableassign_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableassign',
            name='assigned',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
