# Generated by Django 6.0 on 2025-12-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0005_remove_tableassign_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='assigned',
        ),
        migrations.AddField(
            model_name='tableassign',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
