# Generated by Django 6.0 on 2025-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0006_remove_tablereservation_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableassign',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
