# Generated by Django 5.2.9 on 2025-12-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0007_tableassign_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableassign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
