# Generated by Django 5.2.9 on 2025-12-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0008_tablereservation_seat_alter_tableassign_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
