# Generated by Django 5.2.9 on 2025-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0009_tablereservation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='time_schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
