# Generated by Django 5.2.9 on 2025-12-22 03:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_reservation', '0011_alter_tableassign_id_alter_tablereservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
