# Generated by Django 6.0 on 2025-12-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='menu_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TableLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('Location', models.CharField(choices=[('Window_side', 'Window_side'), ('roof_top', 'roof_top'), ('indoor', 'indoor'), ('outdoor', 'outdoor'), ('suit_space', 'suit_space')], max_length=100)),
                ('capacity', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
