# Generated by Django 6.0 on 2025-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_menu_tablelayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablelayout',
            name='id',
        ),
        migrations.AddField(
            model_name='tablelayout',
            name='floor_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tablelayout',
            name='table_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
