# Generated by Django 6.0 on 2025-12-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_tablelayout_id_tablelayout_floor_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('kitchen_staff', 'kitchen_staff'), ('waiter', 'waiter'), ('guest', 'guest')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
