# Generated by Django 6.0 on 2025-12-10 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_category',
            field=models.CharField(blank=True, choices=[('starters', 'starters'), ('main_course', 'main_course'), ('dessert', 'dessert'), ('side_dish', 'side_dish'), ('indian', 'indian'), ('chinese', 'chinese'), ('italian', 'italian'), ('japanese', 'japanese')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_type',
            field=models.CharField(blank=True, choices=[('veg', 'veg'), ('non-veg', 'non-veg')], max_length=100, null=True),
        ),
    ]
