# Generated by Django 6.0.5 on 2026-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_phase3_model_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kitchen_staff', 'Kitchen Staff'), ('waiter', 'Waiter'), ('guest', 'Guest')], max_length=20),
        ),
    ]
