# Generated by Django 6.0.5 on 2026-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablelayout',
            name='Location',
            field=models.CharField(choices=[('Window_side', 'Window_side'), ('roof_top', 'roof_top'), ('indoor', 'indoor'), ('outdoor', 'outdoor'), ('suit_space', 'suit_space'), ('restaurant', 'Restaurant Setup'), ('party_setup', 'Party Setup')], max_length=100),
        ),
    ]
