# Generated by Django 5.2.9 on 2025-12-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='cart_user',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='orders.cart_user'),
            preserve_default=False,
        ),
    ]
