# Generated by Django 6.0.5 on 2026-08-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_created_at_order_kitchen_staff_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='vechile_number',
            new_name='vehicle_number',
        ),
    ]
