# Generated by Django 6.0.5 on 2026-08-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_phase3_model_updates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orderkitchenstaff',
            table=None,
        ),
    ]
